[workspace]
members = [
    "crates/stainless-build",
    "crates/stainless-compiler",
    "crates/stainless-kvstore",
    "crates/stainless-runtime",
    "crates/stainless-syntax",
    "crates/stainlessc",
]
resolver = "3"

[workspace.package]
edition = "2024"
license = "MIT"
rust-version = "1.97"

[workspace.dependencies]
logos = "0.16.1"
prettyplease = "0.2.37"
proc-macro2 = "1.0.107"
quote = "1.0.47"
regex = "1.12.4"
rowan = "0.16.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = { version = "1.0.151", features = ["arbitrary_precision"] }
syn = { version = "2.0.119", features = ["full"] }
toml = "1.1.2"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"
