[package]
name = "stainless-compiler"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
prettyplease.workspace = true
proc-macro2.workspace = true
quote.workspace = true
stainless-syntax = { path = "../stainless-syntax" }
syn.workspace = true
